### ISSUE TITLE
What ever happened to this project?

### ISSUE THREAD

**Issue by pgporada** [srvaudit/srvAudit#2]
^

**Comment by codercotton** [comment]
Hey pgporada - I'm still working on this as time allows, and plan another release in the next couple of months.  If you're willing to help or at least talk about your needs a bit, it'd be much appreciated!

**Comment by pgporada** [comment]
I'm primarily a systems administrator that writes shell scripts and use Ansible for automation. I could help out with those aspects. I gave your tool a shot last night on a throwaway box. I saw in the installcentos script that you send out a message to your own slack channel when someone installs the software. Did you actually happen to get that?

**Comment by codercotton** [comment]
We did see it in our Slack!  Thanks for the offer - were you able to get the test instance up?  That installer is a bit dated, granted... and you'd need a Redmine instance.

**Comment by pgporada** [comment]
I did get it up and then destroyed the instance. I needed to run some SELinux commands to get it working because sshd was unable to use `getaddr`. I saw your comment in the install script, but that didn't work for me. I'll have to reproduce it to get the commands again.

From my perspective, it would be useful if a person could disable the ticket system integration altogether. At my current job, we use Ansible to deploy software from Jenkins on a cron. We'd generate a ton of tickets for no reason other than running Ansible. We can live with the slack notifications.

**Comment by pgporada** [comment]
I'm unsure of where the `environment: dev` piece came from. 

http://imgur.com/a/4Mqc1

**Comment by codercotton** [comment]
That Dev flag is hard-coded currently (in /srv/audit/slack).  We'll make that configurable via /etc/srvaudit/config in the next release.

**Comment by codercotton** [comment]
Feel free to submit a PR with any suggestions!
